### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/service-template-node#106]
Is it worth doing a new service-template-node release? https://github.com/wikimedia/service-template-node/compare/v0.5.4...master has a few changes.

**Comment by d00rman** [comment]
We are now on v0.5.5 but some further changes (thnx to you!) have accumulated as well. I will release v0.5.6 shortly

**Comment by d00rman** [comment]
[v0.5.6](https://github.com/wikimedia/service-template-node/tree/v0.5.6) has been released ;)
