### ISSUE TITLE
Request-id only logged on init? 

### ISSUE THREAD

**Issue by mvolz** [wikimedia/service-template-node#128]
Request id seems to be only logged once here, on receiving the request: https://github.com/wikimedia/service-template-node/blob/master/lib/util.js#L235

But it would be really great if it were logged throughout the route, so that it would be possible to identify particular logs, i.e. warns or errors, with the particular request that was made. 

Any idea on how best to accomplish  this?

**Comment by akosiaris** [comment]
@Pchelolo any chance you can help with this?

**Comment by Pchelolo** [comment]
Moved onto Phab for better tracking https://phabricator.wikimedia.org/T247590
