### ISSUE TITLE
Config.dev.yaml and config.prod.yaml need updating to remove references to logstash

### ISSUE THREAD

**Issue by mvolz** [wikimedia/service-template-node#136]
https://github.com/wikimedia/service-template-node/blob/69a09dd2b463786a1f86c4c80cf2d6d7054e4b4b/config.dev.yaml#L14

Restbase will also need to be updated to 2.7.7 to accompany this change as per https://phabricator.wikimedia.org/T239459

See also: 
https://phabricator.wikimedia.org/T227080
https://phabricator.wikimedia.org/T219919

**Comment by nikkhn** [comment]
This issue has been moved to Phabricator [issue](https://phabricator.wikimedia.org/T29015): 6 due to https://phabricator.wikimedia.org/T272230
