### ISSUE TITLE
Make service-template-node non-MediaWiki specific.

### ISSUE THREAD

**Issue by ottomata** [wikimedia/service-template-node#138]
There's nothing in service-template-node that is MediaWiki specific, except for the example configs and routes, and the api-utils (which could be in a separate nodejs module).  I maintain two service-template-node services (EventStreams and EventGate), neither of which is MediaWiki specific.  I'm writing a blog post now about how EventGate which includes info about how it can be used outside of Wikimedia or MediaWiki contexts, and it is a little weird that the parent service-template-node repository has references to MediaWiki.

I'm not really hopeful that this will happen, but I have to try! :)

**Comment by mvolz** [comment]
We don't use the api-utils in citoid either.

**Comment by nikkhn** [comment]
Closed and moved to Phabricator [task](https://phabricator.wikimedia.org/T290159) due to https://phabricator.wikimedia.org/T272230
