### ISSUE TITLE
Pipeline bot causing merge conflicts - should we move repository to gerrit?

### ISSUE THREAD

**Issue by mvolz** [wikimedia/service-template-node#143]
Pipeline bot added tabs to my eslintrc file... should we do just do this upstream here too? 

https://gerrit.wikimedia.org/r/c/mediawiki/services/citoid/+/646877/1/.eslintrc.json

**Comment by mvolz** [comment]
This repo is getting unsynced from most other services because they're on gerrit and pipeline bot is upgrading them. The simplest thing to do seems to be to move this to gerrit - although I guess that can be tabled until the move to gitlab?

**Comment by nikkhn** [comment]
Closed and moved to Phabricator [issue](https://phabricator.wikimedia.org/T290157) due to https://phabricator.wikimedia.org/T272230
