### ISSUE TITLE
Clone `swagger-ui-dist/index.html`; use templates and/or config instead of regex replacements

### ISSUE THREAD

**Issue by flosincapite** [wikimedia/service-template-node#149]
Currently, `lib/util.js` reads the `index.html` file packaged with `swagger-ui`; transforms the contents; then serves the result. This is slow and brittle. Could `index.html` instead be cloned to this repository? That way, the .js script and attendant configuration can be read from separate files.

**Comment by nikkhn** [comment]
Closed and moved to Phabricator [task](https://phabricator.wikimedia.org/T290160) due to https://phabricator.wikimedia.org/T272230.
