### ISSUE TITLE
root rights to run npm install

### ISSUE THREAD

**Issue by physikerwelt** [wikimedia/service-template-node#23]
on labs-vagrant you need root rights to run npm install

**Comment by physikerwelt** [comment]
That could be reflected in the readme

**Comment by d00rman** [comment]
why would you need root rights? there's nothing there that warrants that, AFAIK. No root rights are needed on mw-vagrant.

Could you paste the output, @physikerwelt ?

**Comment by physikerwelt** [comment]
Let me try to reproduce. Maybe it just fails for the first time.

**Comment by physikerwelt** [comment]
strange. Maybe there was an issue with my file system permissions. Can not reproduce.

**Comment by physikerwelt** [comment]
just for reference... it happend again https://gist.github.com/physikerwelt/e1c760ec081950e5f320

**Comment by gwicke** [comment]
Hmm, my guess is that labs-vagrant executes `npm install` as root, which would mess up the permissions. Is this inside of a puppet-managed directory?

**Comment by physikerwelt** [comment]
It's somehow strange that files were in my home directory that I could not overwrite. I'd expect that root would write to  /root/.npm
However, after cleaning my ~/.npm directory I did not have any issues. I guess npm is a little bit like maven, when something breaks delete your ~/.m2 directory.
So it's good that the issue is and remains closed.
