### ISSUE TITLE
Please move non-critical code to other NPMs

### ISSUE THREAD

**Issue by nyurik** [wikimedia/service-template-node#69]
This template is becoming bloated, and it makes it very hard to maintain various services based on it.  For example, `api-util.js` should not be part of the template, as there are no things one should edit in them. Instead, it should be a separate npm module, properly versioned, and referenced from the template if needed.

Please consider restructuring it to remove everything except for the most critical parts. This way merging the new version will not involve reading hundreds of kilobytes of code.

**Comment by nikkhn** [comment]
Migrating repo issues to Phabricator post merge of https://github.com/wikimedia/service-template-node/pull/158
