### ISSUE TITLE
stop server after tests

### ISSUE THREAD

**Issue by physikerwelt** [wikimedia/service-template-node#84]
It would be nice to stop the server after running the tests. 
From mocha version 4 the tests won't finish if the server is not shut down after running all tests.

https://mochajs.org/#--exit----no-exit

https://github.com/wikimedia/service-template-node/blob/43ead9407e81098242b89e44f195785d33000e52/package.json#L48

**Comment by Pchelolo** [comment]
Good observation @physikerwelt will make the server stop.

**Comment by Pchelolo** [comment]
First requirement - add support for graceful shutdown to service-runner: https://github.com/wikimedia/service-runner/pull/167
